"""add provider to agents

Revision ID: 28824b813ed4
Revises: 31356ac1cd47
Create Date: 2026-08-24 18:29:39.091655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28824b813ed4'
down_revision: Union[str, Sequence[str], None] = '31356ac1cd47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('provider', sa.String(length=50), server_default='ollama', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'provider')
    # ### end Alembic commands ###
